<a href="https://colab.research.google.com/github/technerd21/IDS-G-2-Assigns-FA19-BCS-001/blob/main/FA19_BCS_001_Assign4_IDS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install scikit-plot

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
#import libraries
from sklearn import preprocessing
import pandas as pd

#import different ML classifiers
from sklearn.naive_bayes import GaussianNB, BernoulliNB, MultinomialNB
from sklearn.svm import SVC, LinearSVC
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier

#import ML evaluation metrics
from sklearn.metrics import accuracy_score, f1_score,recall_score,precision_score
from sklearn.model_selection import train_test_split
from sklearn import metrics, model_selection
from sklearn.model_selection import ShuffleSplit, cross_val_predict, cross_val_score, LeavePOut

In [3]:
#import library for accesssing Google Drive from Google Colab
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
#read CSV (dataset) file
df_gender = pd.read_csv('/content/drive/My Drive/gender-prediction.csv')
df_gender

height  weight beard hair_length  shoe_size scarf eye_color  gender
0       71     176   yes       short         44    no     black    male
1       68     165    no        bald         41    no     black    male
2       62     132    no      medium         37   yes      blue  female
3       65     138    no        long         38    no      gray  female
4       70     197   yes      medium         43    no      gray    male
..     ...     ...   ...         ...        ...   ...       ...     ...
75      65      99    no       short         39   yes     green  female
76      61      98    no       short         37    no     brown  female
77      67     119   yes       short         40    no     black    male
78      70     190   yes      medium         43    no      gray    male
79      62     142   yes        long         37    no      blue  female

[80 rows x 8 columns]

In [5]:
first_height=df_gender['height']
#first_height
first_weight=df_gender['weight']
#first_weight
first_beard=df_gender['beard']
#first_beard
first_hair_length=df_gender['hair_length']
#first_hair_length
first_shoe_size=df_gender['shoe_size']
#first_shoe_size
first_scarf=df_gender['scarf']
#first_scarf
first_eye_color=df_gender['eye_color']
#first_eye_color
gend_out=df_gender['gender']
gend_out

0       male
1       male
2     female
3     female
4       male
       ...  
75    female
76    female
77      male
78      male
79    female
Name: gender, Length: 80, dtype: object

In [6]:
#converting strings into numbers
labels = preprocessing.LabelEncoder()
beard_encod = labels.fit_transform(first_beard)
print(beard_encod)

hairlength_encod = labels.fit_transform(first_hair_length)
print(hairlength_encod)

scarf_encod = labels.fit_transform(first_scarf)
print(scarf_encod)

eyecolor_encod = labels.fit_transform(first_eye_color)
print(eyecolor_encod)

gender_encod = labels.fit_transform(gend_out)
print(gender_encod)

[1 0 0 0 1 1 1 0 0 0 0 1 0 0 1 1 0 0 0 0 0 1 1 1 0 1 1 0 0 0 0 1 0 0 0 1 0
 1 0 0 0 1 1 1 1 0 0 1 1 1 1 1 0 1 0 0 1 0 1 1 0 1 1 0 0 1 0 1 0 1 0 0 1 0
 0 0 0 1 1 1]
[3 0 2 1 2 3 0 3 3 2 1 3 2 1 2 3 3 1 1 2 2 2 3 2 2 2 2 2 1 3 2 2 1 2 2 2 2
 2 1 2 3 2 2 3 0 2 1 2 2 2 2 2 2 2 1 2 2 1 2 2 2 2 3 1 1 0 1 3 2 3 1 2 2 1
 1 3 3 3 2 1]
[0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 1 0 1
 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0 1 0 1 0 0 0 0 1
 1 1 0 0 0 0]
[0 0 1 3 3 0 2 2 4 3 3 3 0 3 0 1 0 4 3 4 0 0 0 3 2 2 0 4 1 3 2 3 3 0 2 2 4
 0 3 4 3 0 0 2 0 2 0 2 0 0 0 2 2 2 2 0 2 3 2 2 2 2 2 4 3 0 4 0 0 0 2 0 2 3
 4 4 2 0 3 1]
[1 1 0 0 1 1 1 1 0 0 0 1 1 0 1 1 1 0 0 0 0 1 1 1 0 1 1 0 0 0 0 1 0 0 0 1 0
 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 0 1 1 1 1 1 0 0 1 0 1 0 1 0 1 1 0
 0 0 0 1 1 0]


In [7]:
#combining data (inputs ) into single list of tuples
features = list(zip(first_height,first_weight,beard_encod,hairlength_encod,first_shoe_size,scarf_encod,eyecolor_encod))
output_gender =gender_encod 

print(features)
print(output_gender)

[(71, 176, 1, 3, 44, 0, 0), (68, 165, 0, 0, 41, 0, 0), (62, 132, 0, 2, 37, 1, 1), (65, 138, 0, 1, 38, 0, 3), (70, 197, 1, 2, 43, 0, 3), (71, 190, 1, 3, 43, 0, 0), (74, 201, 1, 0, 44, 0, 2), (74, 182, 0, 3, 46, 0, 2), (63, 127, 0, 3, 35, 0, 4), (65, 139, 0, 2, 37, 1, 3), (66, 125, 0, 1, 36, 0, 3), (73, 188, 1, 3, 42, 0, 3), (74, 167, 0, 2, 41, 0, 0), (68, 141, 0, 1, 38, 0, 3), (70, 199, 1, 2, 40, 0, 0), (73, 189, 1, 3, 43, 0, 1), (69, 159, 0, 3, 43, 0, 0), (68, 135, 0, 1, 37, 1, 4), (68, 145, 0, 1, 38, 1, 3), (66, 138, 0, 2, 37, 0, 4), (66, 132, 0, 2, 40, 0, 0), (71, 170, 1, 2, 42, 0, 0), (67, 119, 1, 3, 40, 0, 0), (70, 190, 1, 2, 43, 0, 3), (68, 154, 0, 2, 38, 1, 2), (71, 155, 1, 2, 45, 0, 2), (69, 121, 1, 2, 41, 0, 0), (68, 97, 0, 2, 39, 0, 4), (68, 158, 0, 1, 38, 0, 1), (58, 92, 0, 3, 40, 1, 3), (63, 109, 0, 2, 37, 1, 2), (71, 158, 1, 2, 44, 0, 3), (61, 88, 0, 1, 37, 0, 3), (67, 132, 0, 2, 38, 0, 0), (62, 116, 0, 2, 39, 1, 2), (71, 125, 1, 2, 42, 0, 2), (63, 125, 0, 2, 39, 1, 4), (68

In [8]:
#make train/test split
X_train, x_test, Y_train, y_test = train_test_split(features, output_gender, test_size = 0.33, random_state = 2)

In [9]:
#Random Forest Classifier
model = RandomForestClassifier()

In [10]:
#train the model using the data (training data)
model.fit(X_train,Y_train)

RandomForestClassifier()

In [11]:
#make prediction using the trained model
prediction = model.predict(x_test)

In [12]:
#calcualte and print accuracy
model_acc = accuracy_score(y_test, prediction)*100
print(model_acc)

100.0


In [13]:
#generate classification report
model_cl_rep = metrics.classification_report(y_test, prediction)
print(model_cl_rep)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00        17

    accuracy                           1.00        27
   macro avg       1.00      1.00      1.00        27
weighted avg       1.00      1.00      1.00        27



In [14]:
#generate confusion matrix
model_cm = metrics.confusion_matrix(y_test, prediction)
print(model_cm)

[[10  0]
 [ 0 17]]


In [15]:
#Support Vector Machines
model_SVC=SVC()

In [16]:
#train the model using the data (training data)
model_SVC.fit(X_train,Y_train)

SVC()

In [17]:
#make prediction using the trained model
prediction_SVC = model_SVC.predict(x_test)

In [18]:
#calcualte and print accuracy
model_acc_SVC = accuracy_score(y_test, prediction_SVC)*100
print(model_acc_SVC)

77.77777777777779


In [19]:
#generate classification report
model_cl_rep_SVC = metrics.classification_report(y_test, prediction_SVC)
print(model_cl_rep_SVC)

              precision    recall  f1-score   support

           0       0.70      0.70      0.70        10
           1       0.82      0.82      0.82        17

    accuracy                           0.78        27
   macro avg       0.76      0.76      0.76        27
weighted avg       0.78      0.78      0.78        27



In [20]:
#generate confusion matrix
model_cm_SVC = metrics.confusion_matrix(y_test, prediction_SVC)
print(model_cm_SVC)

[[ 7  3]
 [ 3 14]]


In [21]:
#Linear Support Vector Machines
model_LSVC=LinearSVC()

In [22]:
#train the model using the data (training data)
model_LSVC.fit(X_train,Y_train)

/usr/local/lib/python3.8/dist-packages/sklearn/svm/_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


LinearSVC()

In [23]:
#make prediction using the trained model
prediction_LSVC = model_LSVC.predict(x_test)

In [24]:
#calcualte and print accuracy
model_acc_LSVC = accuracy_score(y_test, prediction_LSVC)*100
print(model_acc_LSVC)

88.88888888888889


In [25]:
#generate classification report
model_cl_rep_LSVC = metrics.classification_report(y_test, prediction_LSVC)
print(model_cl_rep_LSVC)

              precision    recall  f1-score   support

           0       0.82      0.90      0.86        10
           1       0.94      0.88      0.91        17

    accuracy                           0.89        27
   macro avg       0.88      0.89      0.88        27
weighted avg       0.89      0.89      0.89        27



In [26]:
#generate confusion matrix
model_cm_LSVC = metrics.confusion_matrix(y_test, prediction_LSVC)
print(model_cm_LSVC)

[[ 9  1]
 [ 2 15]]


In [27]:
#Multilayer Perceptron classification
model_MLP=MLPClassifier()

In [28]:
#train the model using the data (training data)
model_MLP.fit(X_train,Y_train)

/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier()

In [29]:
#make prediction using the trained model
prediction_MLP = model_MLP.predict(x_test)

In [30]:
#calcualte and print accuracy
model_acc_MLP = accuracy_score(y_test, prediction_MLP)*100
print(model_acc_MLP)

92.5925925925926


In [31]:
#generate classification report
model_cl_rep_MLP = metrics.classification_report(y_test, prediction_MLP)
print(model_cl_rep_MLP)

              precision    recall  f1-score   support

           0       0.90      0.90      0.90        10
           1       0.94      0.94      0.94        17

    accuracy                           0.93        27
   macro avg       0.92      0.92      0.92        27
weighted avg       0.93      0.93      0.93        27



In [32]:
#generate confusion matrix
model_cm_MLP = metrics.confusion_matrix(y_test, prediction_MLP)
print(model_cm_MLP)

[[ 9  1]
 [ 1 16]]


##**Question 2 Using 80/20 Split train/test Ratio**

In [33]:
#make train/test split
Xtw_train, xtw_test, Ytw_train, ytw_test = train_test_split(features, output_gender, test_size = 0.20, random_state = 2)

In [34]:
modeltw_RandomF = RandomForestClassifier()

In [35]:
#train the model using the data (training data)
modeltw_RandomF.fit(Xtw_train,Ytw_train)

RandomForestClassifier()

In [36]:
#make prediction using the trained model
predictiontwRandomF = modeltw_RandomF.predict(xtw_test)

In [37]:
#calcualte and print accuracy
model_acc_twRandomF = accuracy_score(ytw_test, predictiontwRandomF)*100
print(model_acc_twRandomF)

100.0


In [38]:
#generate classification report
model_cl_rep_twRF = metrics.classification_report(ytw_test, predictiontwRandomF)
print(model_cl_rep_twRF)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         6
           1       1.00      1.00      1.00        10

    accuracy                           1.00        16
   macro avg       1.00      1.00      1.00        16
weighted avg       1.00      1.00      1.00        16



In [39]:
#generate confusion matrix
model_cm_twRF = metrics.confusion_matrix(ytw_test, predictiontwRandomF)
print(model_cm_twRF)

[[ 6  0]
 [ 0 10]]


In [40]:
model_twSVC=SVC()

In [41]:
#train the model using the data (training data)
model_twSVC.fit(Xtw_train,Ytw_train)

SVC()

In [42]:
#make prediction using the trained model
predictiontwSVC = model_twSVC.predict(xtw_test)

In [43]:
#calcualte and print accuracy
model_acc_twSVC = accuracy_score(ytw_test, predictiontwSVC)*100
print(model_acc_twSVC)

81.25


In [44]:
#generate classification report
model_cl_rep_twSVC = metrics.classification_report(ytw_test, predictiontwSVC)
print(model_cl_rep_twSVC)

              precision    recall  f1-score   support

           0       0.80      0.67      0.73         6
           1       0.82      0.90      0.86        10

    accuracy                           0.81        16
   macro avg       0.81      0.78      0.79        16
weighted avg       0.81      0.81      0.81        16



In [45]:
#generate confusion matrix
model_cm_twSVC = metrics.confusion_matrix(ytw_test, predictiontwSVC)
print(model_cm_twSVC)

[[4 2]
 [1 9]]


In [141]:
model_twLSVC=LinearSVC()

In [142]:
#train the model using the data (training data)
model_twLSVC.fit(Xtw_train,Ytw_train)

/usr/local/lib/python3.8/dist-packages/sklearn/svm/_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


LinearSVC()

In [143]:
#make prediction using the trained model
predictiontwLSVC = model_twLSVC.predict(xtw_test)

In [144]:
#calcualte and print accuracy
model_acc_twLSVC = accuracy_score(ytw_test, predictiontwLSVC)*100
print(model_acc_twLSVC)

93.75


In [145]:
#generate classification report
model_cl_rep_twLSVC = metrics.classification_report(ytw_test, predictiontwLSVC)
print(model_cl_rep_twLSVC)

              precision    recall  f1-score   support

           0       0.86      1.00      0.92         6
           1       1.00      0.90      0.95        10

    accuracy                           0.94        16
   macro avg       0.93      0.95      0.94        16
weighted avg       0.95      0.94      0.94        16



In [146]:
#generate confusion matrix
model_cm_twLSVC = metrics.confusion_matrix(ytw_test, predictiontwLSVC)
print(model_cm_twLSVC)

[[6 0]
 [1 9]]


In [154]:
model_twMLP=MLPClassifier()

In [155]:
#train the model using the data (training data)
model_twMLP.fit(Xtw_train,Ytw_train)

/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier()

In [156]:
#make prediction using the trained model
predictiontwMLP = model_twMLP.predict(xtw_test)

In [157]:
#calcualte and print accuracy
model_acc_twMLP = accuracy_score(ytw_test, predictiontwMLP)*100
print(model_acc_twMLP)

100.0


In [158]:
#generate classification report
model_cl_rep_twMLP = metrics.classification_report(ytw_test, predictiontwMLP)
print(model_cl_rep_twMLP)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         6
           1       1.00      1.00      1.00        10

    accuracy                           1.00        16
   macro avg       1.00      1.00      1.00        16
weighted avg       1.00      1.00      1.00        16



In [159]:
#generate confusion matrix
model_cm_twMLP = metrics.confusion_matrix(ytw_test, predictiontwMLP)
print(model_cm_twMLP)

[[ 6  0]
 [ 0 10]]


## **Question 2 Using 80/20 Split train/test Ratio Excluding Beard and Scarf Attributes**

In [58]:
#combining data (inputs ) into single list of tuples
features_woutbs = list(zip(first_height,first_weight,hairlength_encod,first_shoe_size,eyecolor_encod))
output_gender =gender_encod 

print(features_woutbs)
print(output_gender)

[(71, 176, 3, 44, 0), (68, 165, 0, 41, 0), (62, 132, 2, 37, 1), (65, 138, 1, 38, 3), (70, 197, 2, 43, 3), (71, 190, 3, 43, 0), (74, 201, 0, 44, 2), (74, 182, 3, 46, 2), (63, 127, 3, 35, 4), (65, 139, 2, 37, 3), (66, 125, 1, 36, 3), (73, 188, 3, 42, 3), (74, 167, 2, 41, 0), (68, 141, 1, 38, 3), (70, 199, 2, 40, 0), (73, 189, 3, 43, 1), (69, 159, 3, 43, 0), (68, 135, 1, 37, 4), (68, 145, 1, 38, 3), (66, 138, 2, 37, 4), (66, 132, 2, 40, 0), (71, 170, 2, 42, 0), (67, 119, 3, 40, 0), (70, 190, 2, 43, 3), (68, 154, 2, 38, 2), (71, 155, 2, 45, 2), (69, 121, 2, 41, 0), (68, 97, 2, 39, 4), (68, 158, 1, 38, 1), (58, 92, 3, 40, 3), (63, 109, 2, 37, 2), (71, 158, 2, 44, 3), (61, 88, 1, 37, 3), (67, 132, 2, 38, 0), (62, 116, 2, 39, 2), (71, 125, 2, 42, 2), (63, 125, 2, 39, 4), (68, 121, 2, 40, 0), (67, 145, 1, 39, 3), (65, 99, 2, 38, 4), (61, 98, 3, 37, 3), (70, 167, 2, 42, 0), (64, 122, 2, 42, 0), (61, 156, 3, 41, 2), (69, 178, 0, 44, 0), (72, 150, 2, 43, 2), (70, 160, 1, 42, 0), (67, 167, 2, 42, 

In [59]:
#make train/test split
Xtwwt_train, xtwwt_test, Ytwwt_train, ytwwt_test = train_test_split(features_woutbs, output_gender, test_size = 0.20, random_state = 2)

In [60]:
modeltwwt_RandomF = RandomForestClassifier()

In [61]:
#train the model using the data (training data)
modeltwwt_RandomF.fit(Xtwwt_train,Ytwwt_train)

RandomForestClassifier()

In [62]:
#make prediction using the trained model
predictiontwwtRandomF = modeltwwt_RandomF.predict(xtwwt_test)

In [63]:
#calcualte and print accuracy
model_acc_twwtRandomF = accuracy_score(ytwwt_test, predictiontwwtRandomF)*100
print(model_acc_twwtRandomF)

100.0


In [64]:
#generate classification report
model_cl_rep_twwtRF = metrics.classification_report(ytwwt_test, predictiontwwtRandomF)
print(model_cl_rep_twwtRF)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         6
           1       1.00      1.00      1.00        10

    accuracy                           1.00        16
   macro avg       1.00      1.00      1.00        16
weighted avg       1.00      1.00      1.00        16



In [65]:
#generate confusion matrix
model_cm_twwtRF = metrics.confusion_matrix(ytwwt_test, predictiontwwtRandomF)
print(model_cm_twwtRF)

[[ 6  0]
 [ 0 10]]


In [160]:
model_twwtSVC=SVC()

In [161]:
#train the model using the data (training data)
model_twwtSVC.fit(Xtwwt_train,Ytwwt_train)

SVC()

In [162]:
#make prediction using the trained model
predictiontwwtSVC = model_twwtSVC.predict(xtwwt_test)

In [163]:
#calcualte and print accuracy
model_acc_twwtSVC = accuracy_score(ytwwt_test, predictiontwwtSVC)*100
print(model_acc_twwtSVC)

81.25


In [164]:
#generate classification report
model_cl_rep_twwtSVC = metrics.classification_report(ytwwt_test, predictiontwwtSVC)
print(model_cl_rep_twwtSVC)

              precision    recall  f1-score   support

           0       0.80      0.67      0.73         6
           1       0.82      0.90      0.86        10

    accuracy                           0.81        16
   macro avg       0.81      0.78      0.79        16
weighted avg       0.81      0.81      0.81        16



In [165]:
#generate confusion matrix
model_cm_twwtSVC = metrics.confusion_matrix(ytwwt_test, predictiontwwtSVC)
print(model_cm_twwtSVC)

[[4 2]
 [1 9]]


In [78]:
model_twwtLSVC=LinearSVC()

In [79]:
#train the model using the data (training data)
model_twwtLSVC.fit(Xtwwt_train,Ytwwt_train)

/usr/local/lib/python3.8/dist-packages/sklearn/svm/_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


LinearSVC()

In [80]:
#make prediction using the trained model
predictiontwwtLSVC = model_twwtLSVC.predict(xtwwt_test)

In [81]:
#calcualte and print accuracy
model_acc_twwtLSVC = accuracy_score(ytwwt_test, predictiontwwtLSVC)*100
print(model_acc_twwtLSVC)

68.75


In [82]:
#generate classification report
model_cl_rep_twwtLSVC = metrics.classification_report(ytwwt_test, predictiontwwtLSVC)
print(model_cl_rep_twwtLSVC)

              precision    recall  f1-score   support

           0       1.00      0.17      0.29         6
           1       0.67      1.00      0.80        10

    accuracy                           0.69        16
   macro avg       0.83      0.58      0.54        16
weighted avg       0.79      0.69      0.61        16



In [83]:
#generate confusion matrix
model_cm_twwtLSVC = metrics.confusion_matrix(ytwwt_test, predictiontwwtLSVC)
print(model_cm_twwtLSVC)

[[ 1  5]
 [ 0 10]]


In [100]:
model_twwtMLP=MLPClassifier()

In [101]:
#train the model using the data (training data)
model_twwtMLP.fit(Xtwwt_train,Ytwwt_train)

MLPClassifier()

In [102]:
#make prediction using the trained model
predictiontwwtMLP = model_twwtMLP.predict(xtwwt_test)

In [103]:
#calcualte and print accuracy
model_acc_twwtMLP = accuracy_score(ytwwt_test, predictiontwwtMLP)*100
print(model_acc_twwtMLP)

75.0


In [104]:
#generate classification report
model_cl_rep_twwtMLP = metrics.classification_report(ytwwt_test, predictiontwwtMLP)
print(model_cl_rep_twwtMLP)

              precision    recall  f1-score   support

           0       1.00      0.33      0.50         6
           1       0.71      1.00      0.83        10

    accuracy                           0.75        16
   macro avg       0.86      0.67      0.67        16
weighted avg       0.82      0.75      0.71        16



In [105]:
#generate confusion matrix
model_cm_twwtMLP = metrics.confusion_matrix(ytwwt_test, predictiontwwtMLP)
print(model_cm_twwtMLP)

[[ 2  4]
 [ 0 10]]


## **Question No 3**

In [106]:
model_DTC = DecisionTreeClassifier()

In [107]:
splitcv=ShuffleSplit(n_splits=10,test_size=0.33,random_state=2)

In [108]:
#monte carlo cross validation
f1_score = cross_val_score(model_DTC, features, output_gender,scoring='f1', cv=splitcv).mean()
f1_score

0.9425376781480785

In [109]:
#LeavePout cross validation
leave_pout = LeavePOut(p=2)  
leave_pout.get_n_splits(features)  


3160

In [ ]:
#f1 score using leave p-out cross validation
f1_score = cross_val_score(model_DTC, features, output_gender,scoring='f1', cv=leave_pout).mean()

In [111]:
f1_score

0.7740506329113924

## **Question 4**

In [123]:
#read CSV (dataset) file
df_gender_updated = pd.read_csv('/content/drive/My Drive/gender_prediction_updated - gender-prediction.csv')
df_gender_updated

height  weight beard hair_length  shoe_size scarf eye_color  gender
0       71     176   yes       short         44    no     black    male
1       68     165    no        bald         41    no     black    male
2       62     132    no      medium         37   yes      blue  female
3       65     138    no        long         38    no      gray  female
4       70     197   yes      medium         43    no      gray    male
..     ...     ...   ...         ...        ...   ...       ...     ...
80      73      96   yes       short         41    no     green    male
81      63     120    no        long         33    no     brown  female
82      59     100    no      medium         42    no     black    male
83      75     130   yes       short         33    no      blue    male
84      60     200    no      medium         40   yes     green  female

[85 rows x 8 columns]

In [124]:
#seperate dependent (output) and independent (input) variables
inp = df_gender_updated.drop('gender', axis=1)
out = pd.DataFrame(df_gender_updated['gender'])
out

gender
0     male
1     male
2   female
3   female
4     male
..     ...
80    male
81  female
82    male
83    male
84  female

[85 rows x 1 columns]

In [126]:
labels = preprocessing.LabelEncoder()
#encoding the categorical attribute of input
inp.beard = labels.fit_transform(inp.beard)
inp.hair_length = labels.fit_transform(inp.hair_length)
inp.scarf = labels.fit_transform(inp.scarf)
inp.eye_color = labels.fit_transform(inp.eye_color)
#encodign the output
out.gender = labels.fit_transform(out.gender)
out

gender
0        1
1        1
2        0
3        0
4        1
..     ...
80       1
81       0
82       1
83       1
84       0

[85 rows x 1 columns]

In [127]:
#accessing a multiple records (rows) from the DataFrame using numerical index
train_up = inp.iloc[:80]
train_output_up = out.iloc[:80]

In [128]:
test_up = inp.iloc[80:]
test_output_up = out.iloc[80:]

In [129]:
model_GNB = GaussianNB()

In [ ]:
model_GNB.fit(train_up,train_output_up)

In [131]:
#make prediction using the gausian trained model
predictions_GNB = model_GNB.predict(test_up)

In [132]:
model_GNB_accuracy = accuracy_score(test_output_up, predictions_GNB)*100
print(model_GNB_accuracy)

100.0


In [133]:
model_GNB_recall = recall_score(test_output_up,predictions_GNB)
model_GNB_recall

1.0

In [134]:
model_GNB_precision = precision_score(test_output_up,predictions_GNB)
model_GNB_precision

1.0