In [87]:
import warnings
warnings.filterwarnings('ignore',category=DeprecationWarning)

import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer,TfidfTransformer
from sklearn.metrics.pairwise import cosine_similarity

# **Question No.1**

In [88]:
S1 ="sunshine state enjoy sunshine"
S2="brown fox jump high, brown fox run"
S3="sunshine state fox run fast"

sentences = np.array([S1,S2,S3])
sentences

array(['sunshine state enjoy sunshine',
       'brown fox jump high, brown fox run',
       'sunshine state fox run fast'], dtype='<U34')

In [90]:
vectorizer = CountVectorizer()
bag_of_words = vectorizer.fit_transform(sentences)
print(vectorizer.get_feature_names())

['brown', 'enjoy', 'fast', 'fox', 'high', 'jump', 'run', 'state', 'sunshine']


In [91]:
print(vectorizer.vocabulary_)

{'sunshine': 8, 'state': 7, 'enjoy': 1, 'brown': 0, 'fox': 3, 'jump': 5, 'high': 4, 'run': 6, 'fast': 2}


In [92]:
print(bag_of_words.toarray())

[[0 1 0 0 0 0 0 1 2]
 [2 0 0 2 1 1 1 0 0]
 [0 0 1 1 0 0 1 1 1]]


In [93]:
BoW = pd.DataFrame(bag_of_words.toarray(),index=['S1','S2','S3'],columns = vectorizer.get_feature_names())
BoW

brown  enjoy  fast  fox  high  jump  run  state  sunshine
S1      0      1     0    0     0     0    0      1         2
S2      2      0     0    2     1     1    1      0         0
S3      0      0     1    1     0     0    1      1         1

In [94]:
#calculating the term frequency
tfidf_vectorizer = TfidfVectorizer(use_idf=False)
tf = tfidf_vectorizer.fit_transform(sentences)
tf

<3x9 sparse matrix of type '<class 'numpy.float64'>'
	with 13 stored elements in Compressed Sparse Row format>

In [95]:
tf_df = pd.DataFrame(tf.toarray(),index=['S1','S2','S3'],columns = vectorizer.get_feature_names())
tf_df

brown     enjoy      fast       fox      high      jump       run  \
S1  0.000000  0.408248  0.000000  0.000000  0.000000  0.000000  0.000000   
S2  0.603023  0.000000  0.000000  0.603023  0.301511  0.301511  0.301511   
S3  0.000000  0.000000  0.447214  0.447214  0.000000  0.000000  0.447214   

       state  sunshine  
S1  0.408248  0.816497  
S2  0.000000  0.000000  
S3  0.447214  0.447214

In [96]:
tf_idf_vectorizers = TfidfVectorizer(use_idf=True)
tf_idf = tf_idf_vectorizers.fit_transform(sentences)
idf = pd.DataFrame({'feature':vectorizer.get_feature_names(), 'idf':tf_idf_vectorizers.idf_})
idf

feature       idf
0     brown  1.693147
1     enjoy  1.693147
2      fast  1.693147
3       fox  1.287682
4      high  1.693147
5      jump  1.693147
6       run  1.287682
7     state  1.287682
8  sunshine  1.287682

In [97]:
#print tfidf
tf_idf_pd = pd.DataFrame(tf_idf.toarray(),index=['S1','S2','S3'],columns = vectorizer.get_feature_names())
tf_idf_pd

brown    enjoy      fast       fox      high      jump       run  \
S1  0.000000  0.50689  0.000000  0.000000  0.000000  0.000000  0.000000   
S2  0.670703  0.00000  0.000000  0.510087  0.335352  0.335352  0.255044   
S3  0.000000  0.00000  0.549351  0.417796  0.000000  0.000000  0.417796   

       state  sunshine  
S1  0.385503  0.771006  
S2  0.000000  0.000000  
S3  0.417796  0.417796

#**Question No.2** 
##Cosine Similarity between S1 and S3

In [98]:
cos_arr = tf.toarray()

In [99]:
cos_arr

array([[0.        , 0.40824829, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.40824829, 0.81649658],
       [0.60302269, 0.        , 0.        , 0.60302269, 0.30151134,
        0.30151134, 0.30151134, 0.        , 0.        ],
       [0.        , 0.        , 0.4472136 , 0.4472136 , 0.        ,
        0.        , 0.4472136 , 0.4472136 , 0.4472136 ]])

In [100]:
print(cosine_similarity([cos_arr[0]], [cos_arr[2]]))

[[0.54772256]]
